echo -e '---\nlayout: tag_index\ntag: novel \n---' > 'novel.md' &
echo -e '---\nlayout: tag_index\ntag: Matlab \n---' > 'Matlab.md' &
echo -e '---\nlayout: tag_index\ntag: wavelet \n---' > 'wavelet.md' &
echo -e '---\nlayout: tag_index\ntag: words \n---' > 'words.md' &
echo -e '---\nlayout: tag_index\ntag: Fedora \n---' > 'Fedora.md' &
echo -e '---\nlayout: tag_index\ntag: VisualBoyAdvance \n---' > 'VisualBoyAdvance.md' &
echo -e '---\nlayout: tag_index\ntag: Naruto \n---' > 'Naruto.md' &
echo -e '---\nlayout: tag_index\ntag: IT++ \n---' > 'IT++.md' &
echo -e '---\nlayout: tag_index\ntag: OpenGL \n---' > 'OpenGL.md' &
echo -e '---\nlayout: tag_index\ntag: memset \n---' > 'memset.md' &
echo -e '---\nlayout: tag_index\ntag: harr \n---' > 'harr.md' &
echo -e '---\nlayout: tag_index\ntag: chm \n---' > 'chm.md' &
echo -e '---\nlayout: tag_index\ntag: fstream \n---' > 'fstream.md' &
echo -e '---\nlayout: tag_index\ntag: MSDN \n---' > 'MSDN.md' &
echo -e '---\nlayout: tag_index\ntag: browser \n---' > 'browser.md' &
echo -e '---\nlayout: tag_index\ntag: quiz \n---' > 'quiz.md' &
echo -e '---\nlayout: tag_index\ntag: C++ \n---' > 'C++.md' &
echo -e '---\nlayout: tag_index\ntag: FFTA \n---' > 'FFTA.md' &
echo -e '---\nlayout: tag_index\ntag: GBA \n---' > 'GBA.md' &
echo -e '---\nlayout: tag_index\ntag: Anvil \n---' > 'Anvil.md' &
echo -e '---\nlayout: tag_index\ntag: Windows \n---' > 'Windows.md' &
echo -e '---\nlayout: tag_index\ntag: C \n---' > 'C.md' &
echo -e '---\nlayout: tag_index\ntag: scanf \n---' > 'scanf.md' &
echo -e '---\nlayout: tag_index\ntag: gcc \n---' > 'gcc.md' &
echo -e '---\nlayout: tag_index\ntag: GNU \n---' > 'GNU.md' &
echo -e '---\nlayout: tag_index\ntag: S-Transform \n---' > 'S-Transform.md' &
echo -e '---\nlayout: tag_index\ntag: FFT \n---' > 'FFT.md' &
echo -e '---\nlayout: tag_index\ntag: media \n---' > 'media.md' &
echo -e '---\nlayout: tag_index\ntag: games \n---' > 'games.md' &
echo -e '---\nlayout: tag_index\ntag: song \n---' > 'song.md' &
echo -e '---\nlayout: tag_index\ntag: sofia-sip \n---' > 'sofia-sip.md' &
echo -e '---\nlayout: tag_index\ntag: C99 \n---' > 'C99.md' &
echo -e '---\nlayout: tag_index\ntag: C++03 \n---' > 'C++03.md' &
echo -e '---\nlayout: tag_index\ntag: sizeof \n---' > 'sizeof.md' &
echo -e '---\nlayout: tag_index\ntag: heart_sutra \n---' > 'heart_sutra.md' &
echo -e '---\nlayout: tag_index\ntag: Trigonometric \n---' > 'Trigonometric.md' &
echo -e '---\nlayout: tag_index\ntag: algorithm \n---' > 'algorithm.md' &
echo -e '---\nlayout: tag_index\ntag: DSP \n---' > 'DSP.md' &
echo -e '---\nlayout: tag_index\ntag: Linux \n---' > 'Linux.md' &
echo -e '---\nlayout: tag_index\ntag: Java \n---' > 'Java.md' &
echo -e '---\nlayout: tag_index\ntag: subprime \n---' > 'subprime.md' &
echo -e '---\nlayout: tag_index\ntag: DC \n---' > 'DC.md' &
echo -e '---\nlayout: tag_index\ntag: economy \n---' > 'economy.md' &
echo -e '---\nlayout: tag_index\ntag: Kubuntu \n---' > 'Kubuntu.md' &
echo -e '---\nlayout: tag_index\ntag: KDE \n---' > 'KDE.md' &
echo -e '---\nlayout: tag_index\ntag: game \n---' > 'game.md' &
echo -e '---\nlayout: tag_index\ntag: S60 \n---' > 'S60.md' &
echo -e '---\nlayout: tag_index\ntag: Google \n---' > 'Google.md' &
echo -e '---\nlayout: tag_index\ntag: vba \n---' > 'vba.md' &
echo -e '---\nlayout: tag_index\ntag: emulator \n---' > 'emulator.md' &
echo -e '---\nlayout: tag_index\ntag: music \n---' > 'music.md' &
echo -e '---\nlayout: tag_index\ntag: photo \n---' > 'photo.md' &
echo -e '---\nlayout: tag_index\ntag: C# \n---' > 'C#.md' &
echo -e '---\nlayout: tag_index\ntag: gmp \n---' > 'gmp.md' &
echo -e '---\nlayout: tag_index\ntag: eMule \n---' > 'eMule.md' &
echo -e '---\nlayout: tag_index\ntag: Wesnoth \n---' > 'Wesnoth.md' &
echo -e '---\nlayout: tag_index\ntag: JPEG \n---' > 'JPEG.md' &
echo -e '---\nlayout: tag_index\ntag: GPS \n---' > 'GPS.md' &
echo -e '---\nlayout: tag_index\ntag: EXIF \n---' > 'EXIF.md' &
echo -e '---\nlayout: tag_index\ntag: puzzle \n---' > 'puzzle.md' &
echo -e '---\nlayout: tag_index\ntag: Dosbox \n---' > 'Dosbox.md' &
echo -e '---\nlayout: tag_index\ntag: tour \n---' > 'tour.md' &
echo -e '---\nlayout: tag_index\ntag: geocaching \n---' > 'geocaching.md' &
echo -e '---\nlayout: tag_index\ntag: perfume \n---' > 'perfume.md' &
echo -e '---\nlayout: tag_index\ntag: augury \n---' > 'augury.md' &
echo -e '---\nlayout: tag_index\ntag: kdevelop \n---' > 'kdevelop.md' &
echo -e '---\nlayout: tag_index\ntag: ubuntu \n---' > 'ubuntu.md' &
echo -e '---\nlayout: tag_index\ntag: Symbian \n---' > 'Symbian.md' &
echo -e '---\nlayout: tag_index\ntag: wordpress \n---' > 'wordpress.md' &
echo -e '---\nlayout: tag_index\ntag: registry \n---' > 'registry.md' &
echo -e '---\nlayout: tag_index\ntag: BSOD \n---' > 'BSOD.md' &
echo -e '---\nlayout: tag_index\ntag: gate \n---' > 'gate.md' &
echo -e '---\nlayout: tag_index\ntag: Jenkins \n---' > 'Jenkins.md' &
echo -e '---\nlayout: tag_index\ntag: email \n---' > 'email.md' &
echo -e '---\nlayout: tag_index\ntag: Gogs \n---' > 'Gogs.md' &
echo -e '---\nlayout: tag_index\ntag: git \n---' > 'git.md' &
echo -e '---\nlayout: tag_index\ntag: sso \n---' > 'sso.md' &
echo -e '---\nlayout: tag_index\ntag: SVN \n---' > 'SVN.md' &
echo -e '---\nlayout: tag_index\ntag: CentOS \n---' > 'CentOS.md' &
echo -e '---\nlayout: tag_index\ntag: SonarQube \n---' > 'SonarQube.md' &
echo -e '---\nlayout: tag_index\ntag: coverage \n---' > 'coverage.md' &